! generated by Array Compiler
module _tmp_xamerican
use kind_mod, only: dp
use ac_string_mod, only: ac_lower, ac_format_default, ac_format_fixed, &
    & ac_format_scientific, ac_format_int, ac_format_array, &
    & ac_set_printoptions
implicit none

private
public :: binomial_tree_option_price, print_example, run_example
public :: run_main

contains

function binomial_tree_option_price(spot, strike, rate, dividend_yield, &
    & volatility, time_to_maturity, num_steps, option_type, exercise_style) &
    & result(result_value)
! Price a European or American call or put with a CRR binomial tree.
real(dp), intent(in) :: spot, strike, rate, dividend_yield, volatility, &
    & time_to_maturity
integer, intent(in) :: num_steps
character(len=*), intent(in) :: option_type, exercise_style
real(dp) :: result_value
character(len=:), allocatable :: option_kind, style
real(dp) :: dt, up, down, discount, growth, risk_neutral_prob, terminal_price, &
    & continuation_value, stock_price, intrinsic_value
real(dp), allocatable :: values(:), next_values(:)
integer :: num_down_moves, step, node
if (spot <= 0.0d0) error stop "spot must be > 0"
if (strike <= 0.0d0) error stop "strike must be > 0"
if (volatility <= 0.0d0) error stop "volatility must be > 0"
if (time_to_maturity <= 0.0d0) error stop "time_to_maturity must be > 0"
if (num_steps <= 0) error stop "num_steps must be > 0"
option_kind = ac_lower(trim(adjustl(option_type)))
if ((option_kind /= "call") .and. (option_kind /= "put")) error stop &
    & "option_type must be 'call' or 'put'"
style = ac_lower(trim(adjustl(exercise_style)))
if ((style /= "european") .and. (style /= "american")) error stop &
    & "exercise_style must be 'european' or 'american'"
dt = time_to_maturity / num_steps
up = exp(volatility * sqrt(dt))
down = 1.0d0 / up
discount = exp(-rate * dt)
growth = exp((rate - dividend_yield) * dt)
risk_neutral_prob = (growth - down) / (up - down)
if (.not. ((0.0d0 < risk_neutral_prob) .and. (risk_neutral_prob < 1.0d0))) &
    & error stop "risk-neutral probability must lie strictly between 0 and 1"
values = [real(dp) :: ]
do num_down_moves = 0, num_steps
    terminal_price = spot * up ** (num_steps - num_down_moves) * down ** &
    & num_down_moves
    if (option_kind == "call") then
        values = [values, max(terminal_price - strike, 0.0d0)]
    else
        values = [values, max(strike - terminal_price, 0.0d0)]
    end if
end do
do step = num_steps - 1, merge((-1 - 1), (-1 + 1), (-1 > 0)), -1
    next_values = [real(dp) :: ]
    do node = 0, step
        continuation_value = discount * (risk_neutral_prob * values(node + 1) &
    & + (1.0d0 - risk_neutral_prob) * values(node + 2))
        if (style == "american") then
            stock_price = spot * up ** (step - node) * down ** node
            if (option_kind == "call") then
                intrinsic_value = max(stock_price - strike, 0.0d0)
            else
                intrinsic_value = max(strike - stock_price, 0.0d0)
            end if
            next_values = [next_values, max(continuation_value, &
    & intrinsic_value)]
        else
            next_values = [next_values, continuation_value]
        end if
    end do
    values = next_values
end do
result_value = values(1)
end function binomial_tree_option_price

subroutine print_example(dividend_yield)
! Price European and American calls and puts for one dividend yield.
real(dp), intent(in) :: dividend_yield
real(dp), parameter :: spot = 100.0d0, strike = 100.0d0, rate = 0.05d0, &
    & volatility = 0.2d0, time_to_maturity = 1.0d0
integer, parameter :: num_steps = 10000
real(dp) :: european_call, american_call, european_put, american_put, &
    & discounted_spot, discounted_strike, european_parity_left, &
    & european_parity_right, european_parity_error, american_parity_value, &
    & american_parity_lower, american_parity_upper
european_call = binomial_tree_option_price(spot, strike, rate, dividend_yield, &
    & volatility, time_to_maturity, num_steps, "call", "european")
american_call = binomial_tree_option_price(spot, strike, rate, dividend_yield, &
    & volatility, time_to_maturity, num_steps, "call", "american")
european_put = binomial_tree_option_price(spot, strike, rate, dividend_yield, &
    & volatility, time_to_maturity, num_steps, "put", "european")
american_put = binomial_tree_option_price(spot, strike, rate, dividend_yield, &
    & volatility, time_to_maturity, num_steps, "put", "american")
discounted_spot = spot * exp(-dividend_yield * time_to_maturity)
discounted_strike = strike * exp(-rate * time_to_maturity)
european_parity_left = european_call - european_put
european_parity_right = discounted_spot - discounted_strike
european_parity_error = abs(european_parity_left - european_parity_right)
american_parity_value = american_call - american_put
american_parity_lower = discounted_spot - strike
american_parity_upper = spot - discounted_strike
write(*, "(a)") "dividend_yield: " // ac_format_fixed(dividend_yield, 4)
write(*, "(a)") "num_steps:      " // ac_format_default(num_steps)
write(*, "(a)") "european call:  " // ac_format_fixed(european_call, 10)
write(*, "(a)") "american call:  " // ac_format_fixed(american_call, 10)
write(*, "(a)") "call premium:   " // ac_format_fixed(american_call - &
    & european_call, 10)
write(*, "(a)") "european put:   " // ac_format_fixed(european_put, 10)
write(*, "(a)") "american put:   " // ac_format_fixed(american_put, 10)
write(*, "(a)") "put premium:    " // ac_format_fixed(american_put - &
    & european_put, 10)
write(*, "(a)") "eu parity lhs:  " // ac_format_fixed(european_parity_left, 10)
write(*, "(a)") "eu parity rhs:  " // ac_format_fixed(european_parity_right, 10)
write(*, "(a)") "eu abs error:   " // &
    & ac_format_scientific(european_parity_error, 10)
write(*, "(a)") "am parity val:  " // ac_format_fixed(american_parity_value, 10)
write(*, "(a)") "am parity low:  " // ac_format_fixed(american_parity_lower, 10)
write(*, "(a)") "am parity high: " // ac_format_fixed(american_parity_upper, 10)
if ((american_call + 1d-12) < european_call) error stop &
    & "American call price should not be below European call price"
if ((american_put + 1d-12) < european_put) error stop &
    & "American put price should not be below European put price"
if (european_parity_error > 1d-10) error stop &
    & "European put-call parity check failed"
if (american_parity_value < (american_parity_lower - 1d-10)) error stop &
    & "American put-call parity lower bound failed"
if (american_parity_value > (american_parity_upper + 1d-10)) error stop &
    & "American put-call parity upper bound failed"
write(*, "(a)") "American prices are at least as large as European prices"
write(*, "(a)") "European parity equality and American parity bounds passed"
end subroutine print_example

subroutine run_example()
! Show no-dividend and dividend-paying examples.
call print_example(0.0d0)
print *
call print_example(0.08d0)
end subroutine run_example

subroutine run_main()
call run_example()
end subroutine run_main

end module _tmp_xamerican
