! generated by Array Compiler
module t001_scalar_and_dtype_p
use kind_mod, only: dp
use ac_string_mod, only: ac_lower, ac_format_default, ac_format_fixed, &
    & ac_format_scientific, ac_format_int, ac_format_array, &
    & ac_set_printoptions
use ac_numpy_mod
implicit none

private
public :: run_main

contains

subroutine run_main()
real(dp), allocatable :: x(:), y(:)
call ac_set_printoptions(6, .true., 120, .true., .true., .true.)
x = [1, 2, 3]
y = ac_asarray(x) * 0.5d0
write(*, "(a)") "x " // ac_format_array(x) // " int32"
write(*, "(a)") "y " // ac_format_array(y) // " float64"
end subroutine run_main

end module t001_scalar_and_dtype_p
