! generated by Array Compiler
module t040_local
use kind_mod, only: dp
use ac_string_mod, only: ac_lower, ac_format_default, ac_format_fixed, &
    & ac_format_scientific, ac_format_int, ac_format_array, &
    & ac_set_printoptions
use ac_numpy_mod
implicit none

private
public :: foo
public :: run_main

contains

pure elemental function foo(a) result(result_value)
real(dp), intent(in) :: a
real(dp) :: result_value
result_value = a * a + 2.0d0 * a + 1.0d0
end function foo

subroutine run_main()
real(dp), allocatable :: x(:)
real(dp) :: y
call ac_set_printoptions(6, .true., 120, .true., .true., .true.)
x = ac_linspace(-2.0d0, 2.0d0, 5)
y = foo(x)
write(*, "(a)") "x " // ac_format_array(x)
write(*, "(a)") "y " // ac_format_default(y)
end subroutine run_main

end module t040_local
