! generated by Array Compiler
module xar_sim_p
use kind_mod, only: dp
use ac_string_mod, only: ac_lower, ac_format_default, ac_format_fixed, &
    & ac_format_scientific, ac_format_int, ac_format_array, &
    & ac_set_printoptions
use ac_random_support, only: ac_random_state, ac_random_init, ac_gauss
use ac_numpy_mod
implicit none

private
public :: is_stationary_ar, simulate_arp, empirical_acf, theoretical_acf_ar, &
    & compare_acf, main
public :: run_main

contains

pure function is_stationary_ar(phi) result(result_value)
real(dp), intent(in) :: phi(:)
real(dp), allocatable :: poly(:)
complex(dp), allocatable :: roots(:)
logical :: result_value
poly = ac_r_concat(-ac_reverse(phi), 1.0d0)
roots = ac_roots(poly)
result_value = all(abs(roots) > 1.0d0)
end function is_stationary_ar

function simulate_arp(n, phi, sigma, x0, burn, seed) result(result_value)
integer, intent(in) :: n
real(dp), intent(in) :: phi(:), sigma, x0(:)
integer, intent(in) :: burn, seed
integer :: p, total
type(ac_random_state) :: rng
real(dp), allocatable :: eps(:), x(:)
integer :: t
real(dp), allocatable :: result_value(:)
p = size(phi)
if (p == 0) error stop "phi must have positive length"
if (.not. is_stationary_ar(phi)) error stop &
    & "phi does not define a stationary ar(p) process"
total = (n + burn) + p
rng = ac_random_init(seed)
eps = ac_normal_vec(rng, 0.0d0, sigma, total)
x = ac_zeros(total)
if (size(x0) > 0) then
    if (size(x0) /= p) error stop "x0 must have length len(phi)"
    call ac_set_slice(x, 0, p, x0)
end if
do t = p, (total - 1), 1
    x(t + 1) = ac_dot(phi, ac_reverse(ac_slice(x, t - p, t))) + eps(t + 1)
end do
result_value = ac_slice(x, burn + p, size(x))
end function simulate_arp

pure function empirical_acf(x, k) result(result_value)
real(dp), intent(in) :: x(:)
integer, intent(in) :: k
integer :: n
real(dp), allocatable :: xc(:)
real(dp) :: denom
real(dp), allocatable :: acf(:)
integer :: lag
real(dp), allocatable :: result_value(:)
n = size(x)
if (k >= n) error stop "k must be less than len(x)"
xc = x - ac_mean(x)
denom = ac_dot(xc, xc)
acf = ac_empty(k)
do lag = 1, (k + 1 - 1), 1
    acf(lag - 1 + 1) = ac_dot(ac_slice(xc, 0, -lag), ac_slice(xc, lag, &
    & size(xc))) / denom
end do
result_value = acf
end function empirical_acf

pure function theoretical_acf_ar(phi, k) result(result_value)
real(dp), intent(in) :: phi(:)
integer, intent(in) :: k
integer :: p
real(dp), allocatable :: a(:, :), b(:)
integer :: h, j, m
real(dp), allocatable :: rho_1_to_p(:)
integer :: kmax
real(dp), allocatable :: rho(:)
real(dp) :: s
real(dp), allocatable :: result_value(:)
p = size(phi)
if (p == 0) error stop "phi must have positive length"
if (.not. is_stationary_ar(phi)) error stop &
    & "phi does not define a stationary ar(p) process"
a = ac_zeros2(p, p)
b = ac_zeros(p)
do h = 1, (p + 1 - 1), 1
    call ac_set_item2(a, h - 1, h - 1, 1.0d0)
    do j = 1, (p + 1 - 1), 1
        m = abs(h - j)
        if (m == 0) then
            b(h - 1 + 1) = b(h - 1 + 1) + phi(j - 1 + 1)
        else
            call ac_set_item2(a, h - 1, m - 1, ac_item2(a, h - 1, m - 1) - &
    & phi(j - 1 + 1))
        end if
    end do
end do
rho_1_to_p = ac_solve_linear(a, b)
kmax = max(k, p)
rho = ac_empty(kmax + 1)
rho(0 + 1) = 1.0d0
call ac_set_slice(rho, 1, p + 1, rho_1_to_p)
do h = p + 1, (kmax + 1 - 1), 1
    s = 0.0d0
    do j = 1, (p + 1 - 1), 1
        s = s + phi(j - 1 + 1) * rho(h - j + 1)
    end do
    rho(h + 1) = s
end do
result_value = ac_slice(rho, 1, k + 1)
end function theoretical_acf_ar

pure function compare_acf(x, phi, k) result(result_value)
real(dp), intent(in) :: x(:), phi(:)
integer, intent(in) :: k
real(dp), allocatable :: emp(:), theo(:), diff(:), lags(:)
real(dp), allocatable :: result_value(:, :)
emp = empirical_acf(x, k)
theo = theoretical_acf_ar(phi, k)
diff = emp - theo
lags = ac_arange(1, k + 1)
result_value = ac_column_stack(lags, emp, theo, diff)
end function compare_acf

subroutine main()
integer, parameter :: n = 500000
real(dp), allocatable :: phi(:)
real(dp) :: sigma
integer :: k, seed
real(dp), allocatable :: x(:), table(:, :), row(:)
integer :: row_index
real(dp) :: lag, emp, theo, diff
phi = ac_array([0.7d0, -0.2d0, 0.1d0])
sigma = 1.0d0
k = 5
seed = 123
x = simulate_arp(n, phi, sigma, ac_zeros(0), 1000, seed)
table = compare_acf(x, phi, k)
write(*, "(a)") "phi =" // " " // ac_format_array(phi)
write(*, "(a)") "stationary =" // " " // &
    & ac_format_default(is_stationary_ar(phi))
print *
write(*, "(a)") "first 10 simulated values:"
write(*, "(a)") ac_format_array(ac_round(ac_slice(x, 0, 10), 4))
print *
write(*, "(a)") " lag    empirical    theoretical    difference"
do row_index = 0, (ac_shape_dim(table, 1) - 1), 1
    row = ac_row(table, row_index)
    if (.true.) then
        lag = row(0 + 1)
        emp = row(1 + 1)
        theo = row(2 + 1)
        diff = row(3 + 1)
    end if
    write(*, "(a)") ac_format_int(int(lag), 4) // "   " // &
    & ac_format_default(emp) // "   " // ac_format_default(theo) // "   " // &
    & ac_format_default(diff)
end do
end subroutine main

subroutine run_main()
call ac_set_printoptions(4, .true., 60, .true., .true., .true.)
call main()
end subroutine run_main

end module xar_sim_p
