! generated by Array Compiler
module xar_sim_acf_pacf_p
use kind_mod, only: dp
use ac_string_mod, only: ac_lower, ac_format_default, ac_format_fixed, &
    & ac_format_scientific, ac_format_int, ac_format_array, &
    & ac_set_printoptions
use ac_random_support, only: ac_random_state, ac_random_init, ac_gauss
use ac_numpy_mod
implicit none

private
public :: is_stationary_ar, simulate_arp, empirical_acf, theoretical_acf_ar, &
    & pacf_from_acf, empirical_pacf, theoretical_pacf_ar, compare_values, &
    & print_table, main
public :: run_main

contains

pure function is_stationary_ar(phi) result(result_value)
real(dp), intent(in) :: phi(:)
real(dp), allocatable :: poly(:)
complex(dp), allocatable :: roots(:)
logical :: result_value
poly = ac_r_concat(-ac_reverse(phi), 1.0d0)
roots = ac_roots(poly)
result_value = all(abs(roots) > 1.0d0)
end function is_stationary_ar

function simulate_arp(n, phi, sigma, x0, burn, seed) result(result_value)
integer, intent(in) :: n
real(dp), intent(in) :: phi(:), sigma, x0(:)
integer, intent(in) :: burn, seed
integer :: p, total
type(ac_random_state) :: rng
real(dp), allocatable :: eps(:), x(:)
integer :: t
real(dp), allocatable :: result_value(:)
p = size(phi)
if (p == 0) error stop "phi must have positive length"
if (.not. is_stationary_ar(phi)) error stop &
    & "phi does not define a stationary ar(p) process"
total = (n + burn) + p
rng = ac_random_init(seed)
eps = ac_normal_vec(rng, 0.0d0, sigma, total)
x = ac_zeros(total)
if (size(x0) > 0) then
    if (size(x0) /= p) error stop "x0 must have length len(phi)"
    call ac_set_slice(x, 0, p, x0)
end if
do t = p, (total - 1), 1
    x(t + 1) = ac_dot(phi, ac_reverse(ac_slice(x, t - p, t))) + eps(t + 1)
end do
result_value = ac_slice(x, burn + p, size(x))
end function simulate_arp

pure function empirical_acf(x, k) result(result_value)
real(dp), intent(in) :: x(:)
integer, intent(in) :: k
integer :: n
real(dp), allocatable :: xc(:)
real(dp) :: denom
real(dp), allocatable :: acf(:)
integer :: lag
real(dp), allocatable :: result_value(:)
n = size(x)
if (k >= n) error stop "k must be less than len(x)"
xc = x - ac_mean(x)
denom = ac_dot(xc, xc)
acf = ac_empty(k)
do lag = 1, (k + 1 - 1), 1
    acf(lag - 1 + 1) = ac_dot(ac_slice(xc, 0, -lag), ac_slice(xc, lag, &
    & size(xc))) / denom
end do
result_value = acf
end function empirical_acf

pure function theoretical_acf_ar(phi, k) result(result_value)
real(dp), intent(in) :: phi(:)
integer, intent(in) :: k
integer :: p
real(dp), allocatable :: a(:, :), b(:)
integer :: h, j, m
real(dp), allocatable :: rho_1_to_p(:)
integer :: kmax
real(dp), allocatable :: rho(:)
real(dp), allocatable :: result_value(:)
p = size(phi)
if (p == 0) error stop "phi must have positive length"
if (.not. is_stationary_ar(phi)) error stop &
    & "phi does not define a stationary ar(p) process"
a = ac_zeros2(p, p)
b = ac_zeros(p)
do h = 1, (p + 1 - 1), 1
    call ac_set_item2(a, h - 1, h - 1, 1.0d0)
    do j = 1, (p + 1 - 1), 1
        m = abs(h - j)
        if (m == 0) then
            b(h - 1 + 1) = b(h - 1 + 1) + phi(j - 1 + 1)
        else
            call ac_set_item2(a, h - 1, m - 1, ac_item2(a, h - 1, m - 1) - &
    & phi(j - 1 + 1))
        end if
    end do
end do
rho_1_to_p = ac_solve_linear(a, b)
kmax = max(k, p)
rho = ac_empty(kmax + 1)
rho(0 + 1) = 1.0d0
call ac_set_slice(rho, 1, p + 1, rho_1_to_p)
do h = p + 1, (kmax + 1 - 1), 1
    rho(h + 1) = ac_dot(phi, rho(h:h - (p + 1) + 2:-1))
end do
result_value = ac_slice(rho, 1, k + 1)
end function theoretical_acf_ar

pure function pacf_from_acf(rho) result(result_value)
real(dp), intent(in) :: rho(:)
integer :: k
real(dp), allocatable :: phi_mat(:, :), pacf(:)
real(dp) :: v
integer :: m
real(dp) :: num
integer :: j
real(dp) :: den
real(dp), allocatable :: result_value(:)
k = size(rho) - 1
if (k < 1) then
    result_value = ac_zeros(0)
    return
end if
phi_mat = ac_zeros2(k + 1, k + 1)
pacf = ac_zeros(k + 1)
call ac_set_item2(phi_mat, 1, 1, rho(1 + 1))
pacf(1 + 1) = rho(1 + 1)
v = 1.0d0 - (rho(1 + 1) ** 2)
do m = 2, (k + 1 - 1), 1
    num = rho(m + 1)
    do j = 1, (m - 1), 1
        num = num - ac_item2(phi_mat, m - 1, j) * rho(m - j + 1)
    end do
    den = v
    call ac_set_item2(phi_mat, m, m, num / den)
    pacf(m + 1) = ac_item2(phi_mat, m, m)
    do j = 1, (m - 1), 1
        call ac_set_item2(phi_mat, m, j, ac_item2(phi_mat, m - 1, j) - &
    & (ac_item2(phi_mat, m, m) * ac_item2(phi_mat, m - 1, m - j)))
    end do
    v = v * (1.0d0 - (ac_item2(phi_mat, m, m) ** 2))
end do
result_value = ac_slice(pacf, 1, size(pacf))
end function pacf_from_acf

pure function empirical_pacf(x, k) result(result_value)
real(dp), intent(in) :: x(:)
integer, intent(in) :: k
real(dp), allocatable :: acf(:), rho(:)
real(dp), allocatable :: result_value(:)
acf = empirical_acf(x, k)
rho = ac_empty(k + 1)
rho(0 + 1) = 1.0d0
call ac_set_slice(rho, 1, size(rho), acf)
result_value = pacf_from_acf(rho)
end function empirical_pacf

function theoretical_pacf_ar(phi, k) result(result_value)
real(dp), intent(in) :: phi(:)
integer, intent(in) :: k
real(dp), allocatable :: acf(:), rho(:), pacf(:)
integer :: p
real(dp), allocatable :: result_value(:)
acf = theoretical_acf_ar(phi, k)
rho = ac_empty(k + 1)
rho(0 + 1) = 1.0d0
call ac_set_slice(rho, 1, size(rho), acf)
pacf = pacf_from_acf(rho)
p = size(phi)
if (k > p) pacf((p) + 1:size(pacf)) = 0.0d0
result_value = pacf
end function theoretical_pacf_ar

pure function compare_values(emp, theo) result(result_value)
real(dp), intent(in) :: emp(:), theo(:)
integer :: k
real(dp), allocatable :: lags(:), diff(:)
real(dp), allocatable :: result_value(:, :)
if (size(emp) /= size(theo)) error stop "emp and theo must have the same length"
k = size(emp)
lags = ac_arange(1, k + 1)
diff = emp - theo
result_value = ac_column_stack(lags, emp, theo, diff)
end function compare_values

subroutine print_table(title, table)
character(len=*), intent(in) :: title
real(dp), intent(in) :: table(:, :)
real(dp), allocatable :: row(:)
integer :: row_index
real(dp) :: lag, emp, theo, diff
write(*, "(a)") title
write(*, "(a)") " lag    empirical    theoretical    difference"
do row_index = 0, (ac_shape_dim(table, 1) - 1), 1
    row = ac_row(table, row_index)
    if (.true.) then
        lag = row(0 + 1)
        emp = row(1 + 1)
        theo = row(2 + 1)
        diff = row(3 + 1)
    end if
    write(*, "(a)") ac_format_int(int(lag), 4) // "   " // &
    & ac_format_fixed(emp, 6, 10) // "   " // ac_format_fixed(theo, 6, 11) // &
    & "   " // ac_format_fixed(diff, 6, 11)
end do
print *
end subroutine print_table

subroutine main()
integer, parameter :: n = 5000
real(dp), allocatable :: phi(:)
real(dp) :: sigma
integer :: k, seed
real(dp), allocatable :: x(:), emp_acf(:), theo_acf(:), acf_table(:, :), &
    & emp_pacf(:), theo_pacf(:), pacf_table(:, :)
phi = ac_array([0.7d0, -0.2d0, 0.1d0])
sigma = 1.0d0
k = 10
seed = 123
write(*, "(a)") "n:" // " " // ac_format_int(n, 0)
x = simulate_arp(n, phi, sigma, ac_zeros(0), 1000, seed)
emp_acf = empirical_acf(x, k)
theo_acf = theoretical_acf_ar(phi, k)
acf_table = compare_values(emp_acf, theo_acf)
emp_pacf = empirical_pacf(x, k)
theo_pacf = theoretical_pacf_ar(phi, k)
pacf_table = compare_values(emp_pacf, theo_pacf)
write(*, "(a)") "phi =" // " " // ac_format_array(phi)
write(*, "(a)") "stationary =" // " " // &
    & ac_format_default(is_stationary_ar(phi))
print *
write(*, "(a)") "first 10 simulated values:"
write(*, "(a)") ac_format_array(ac_round(ac_slice(x, 0, 10), 4))
print *
call print_table("acf", acf_table)
call print_table("pacf", pacf_table)
end subroutine main

subroutine run_main()
call main()
end subroutine run_main

end module xar_sim_acf_pacf_p
