! generated by Array Compiler
module xarma_sim_fit_acf_pacf_p
use kind_mod, only: dp
use ac_string_mod, only: ac_lower, ac_format_default, ac_format_fixed, &
    & ac_format_scientific, ac_format_int, ac_format_array, &
    & ac_set_printoptions
use ac_random_support, only: ac_random_state, ac_random_init, ac_gauss
use ac_numpy_mod
implicit none

private
public :: is_stationary_ar, is_invertible_ma, simulate_arma, empirical_acf, &
    & pacf_from_acf, empirical_pacf, impulse_response_arma, &
    & theoretical_acf_arma, theoretical_pacf_arma, yule_walker_ar_start, &
    & split_params, arma_match_objective, local_coordinate_search, &
    & fit_arma_initial_numpy, compare_values, print_table, main
public :: split_params_result, local_coordinate_search_result, &
    & fit_arma_initial_numpy_result
public :: run_main

type :: split_params_result
    real(dp), allocatable :: item1(:)
    real(dp), allocatable :: item2(:)
end type split_params_result

type :: local_coordinate_search_result
    real(dp), allocatable :: item1(:)
    real(dp) :: item2
end type local_coordinate_search_result

type :: fit_arma_initial_numpy_result
    real(dp), allocatable :: ar(:)
    real(dp), allocatable :: ma(:)
    real(dp) :: objective
    real(dp), allocatable :: acf_emp(:)
    real(dp), allocatable :: acf_theo(:)
    real(dp), allocatable :: pacf_emp(:)
    real(dp), allocatable :: pacf_theo(:)
end type fit_arma_initial_numpy_result

contains

pure function is_stationary_ar(ar) result(result_value)
! return true if the ar polynomial has roots outside the unit circle
real(dp), intent(in) :: ar(:)
logical :: result_value
if (size(ar) == 0) then
    result_value = .true.
else
    result_value = all(abs(ac_roots([-ar(size(ar):1:-1), 1.0d0])) > 1.0d0)
end if
end function is_stationary_ar

pure function is_invertible_ma(ma) result(result_value)
! return true if the ma polynomial has roots outside the unit circle
real(dp), intent(in) :: ma(:)
logical :: result_value
if (size(ma) == 0) then
    result_value = .true.
else
    result_value = all(abs(ac_roots([ma(size(ma):1:-1), 1.0d0])) > 1.0d0)
end if
end function is_invertible_ma

function simulate_arma(n, ar_arg, ma_arg, sigma, burn, seed) &
    & result(result_value)
! simulate an arma(p, q) series
!     x[t] = sum ar[i-1] * x[t-i] + eps[t] + sum ma[j-1] * eps[t-j]
integer, intent(in) :: n, burn, seed
real(dp), intent(in) :: ar_arg(:), ma_arg(:), sigma
real(dp), allocatable :: result_value(:)
real(dp), allocatable :: ar(:), ma(:), eps(:), x(:)
integer :: p, q, r, total, t
type(ac_random_state) :: rng
real(dp) :: ar_part, ma_part
ma = ma_arg
ar = ar_arg
if (size(ar) == 0) ar = ac_zeros(0)
if (size(ma) == 0) ma = ac_zeros(0)
if (.not. is_stationary_ar(ar)) error stop &
    & "ar does not define a stationary process"
if (.not. is_invertible_ma(ma)) error stop &
    & "ma does not define an invertible process"
p = size(ar)
q = size(ma)
r = max(p, q)
total = n + burn + r
rng = ac_random_init(seed)
eps = ac_normal_vec(rng, 0.0d0, sigma, total)
x = ac_zeros(total)
do t = r, total - 1
    ar_part = 0.0d0
    if (p > 0) ar_part = sum(ar * x(t:t - p + 1:-1))
    ma_part = eps(t + 1)
    if (q > 0) ma_part = ma_part + sum(ma * eps(t:t - q + 1:-1))
    x(t + 1) = ar_part + ma_part
end do
result_value = x(burn + r + 1:size(x))
end function simulate_arma

pure function empirical_acf(x, k) result(result_value)
! sample acf at lags 1,...,k
real(dp), intent(in) :: x(:)
integer, intent(in) :: k
real(dp), allocatable :: result_value(:)
real(dp), allocatable :: xc(:), acf(:)
real(dp) :: denom
integer :: lag
if (k >= size(x)) error stop "k must be less than len(x)"
xc = x - ac_mean(x)
denom = sum(xc**2)
acf = ac_empty(k)
do lag = 1, k
    acf(lag) = sum(xc(1:size(xc) - lag) * xc(lag + 1:size(xc))) / denom
end do
result_value = acf
end function empirical_acf

pure function pacf_from_acf(rho) result(result_value)
! given rho[0],...,rho[k], return pacf at lags 1,...,k
!     using durbin-levinson recursion
real(dp), intent(in) :: rho(:)
real(dp), allocatable :: result_value(:)
integer :: k, m, j
real(dp), allocatable :: phi(:, :), pacf(:)
real(dp) :: v, num
k = size(rho) - 1
if (k < 1) then
    result_value = ac_zeros(0)
    return
end if
phi = ac_zeros2(k + 1, k + 1)
pacf = ac_zeros(k + 1)
phi(2, 2) = rho(2)
pacf(2) = rho(2)
v = max(1.0d0 - rho(2) ** 2, 1d-12)
do m = 2, k
    num = rho(m + 1)
    do j = 1, m - 1
        num = num - phi(m, j + 1) * rho(m - j + 1)
    end do
    phi(m + 1, m + 1) = num / v
    pacf(m + 1) = phi(m + 1, m + 1)
    do j = 1, m - 1
        phi(m + 1, j + 1) = phi(m, j + 1) - phi(m + 1, m + 1) * phi(m, m - j &
    & + 1)
    end do
    v = max(v * (1.0d0 - phi(m + 1, m + 1) ** 2), 1d-12)
end do
result_value = pacf(2:size(pacf))
end function pacf_from_acf

pure function empirical_pacf(x, k) result(result_value)
! sample pacf at lags 1,...,k
real(dp), intent(in) :: x(:)
integer, intent(in) :: k
real(dp), allocatable :: result_value(:)
result_value = pacf_from_acf([1.0d0, empirical_acf(x, k)])
end function empirical_pacf

pure function impulse_response_arma(ar, ma, npsi) result(result_value)
! return psi[0],...,psi[npsi-1] where
!     x[t] = sum_{j>=0} psi[j] * eps[t-j]
real(dp), intent(in) :: ar(:), ma(:)
integer, intent(in) :: npsi
real(dp), allocatable :: result_value(:)
integer :: p, q, j, m, i
real(dp), allocatable :: psi(:)
real(dp) :: s
p = size(ar)
q = size(ma)
psi = ac_zeros(npsi)
psi(1) = 1.0d0
do j = 1, npsi - 1
    s = 0.0d0
    if (j <= q) s = s + ma(j)
    m = min(p, j)
    do i = 1, m
        s = s + ar(i) * psi(j - i + 1)
    end do
    psi(j + 1) = s
end do
result_value = psi
end function impulse_response_arma

function theoretical_acf_arma(ar, ma, k, npsi_arg) result(result_value)
! approximate theoretical acf at lags 1,...,k using truncated psi weights
real(dp), intent(in) :: ar(:), ma(:)
integer, intent(in) :: k, npsi_arg
real(dp), allocatable :: result_value(:)
integer :: npsi, h
real(dp), allocatable :: psi(:), gamma(:)
npsi = npsi_arg
if (.not. is_stationary_ar(ar)) error stop &
    & "ar does not define a stationary process"
if (.not. is_invertible_ma(ma)) error stop &
    & "ma does not define an invertible process"
if (npsi == -1) npsi = max(500, 50 * (k + 1), 200 * (max(size(ar), size(ma)) &
    & + 1))
psi = impulse_response_arma(ar, ma, npsi)
gamma = ac_empty(k + 1)
do h = 0, k
    gamma(h + 1) = sum(psi(1:npsi - h) * psi(h + 1:size(psi)))
end do
result_value = gamma(2:size(gamma)) / gamma(1)
end function theoretical_acf_arma

function theoretical_pacf_arma(ar, ma, k, npsi) result(result_value)
! theoretical pacf at lags 1,...,k
real(dp), intent(in) :: ar(:), ma(:)
integer, intent(in) :: k, npsi
real(dp), allocatable :: result_value(:)
result_value = pacf_from_acf([1.0d0, theoretical_acf_arma(ar, ma, k, npsi)])
end function theoretical_pacf_arma

function yule_walker_ar_start(acf_emp, p) result(result_value)
! ar(p) start from yule-walker using the first p sample acf values
real(dp), intent(in) :: acf_emp(:)
integer, intent(in) :: p
real(dp), allocatable :: result_value(:)
real(dp), allocatable :: rho(:), rmat(:, :), ar(:)
integer :: i, j
if (p == 0) then
    result_value = ac_zeros(0)
    return
end if
rho = [1.0d0, acf_emp(1:p)]
rmat = ac_empty2(p, p)
do i = 0, p - 1
    do j = 0, p - 1
        rmat(i + 1, j + 1) = rho(abs(i - j) + 1)
    end do
end do
ar = ac_solve_linear_fallback(rmat, rho(2:size(rho)))
ar = ac_clip(ar, -0.9d0, 0.9d0)
if (.not. is_stationary_ar(ar)) ar = 0.0d0
result_value = ar
end function yule_walker_ar_start

pure function split_params(params, p, q) result(result_value)
! split parameter vector into ar and ma parts
real(dp), intent(in) :: params(:)
integer, intent(in) :: p, q
type(split_params_result) :: result_value
result_value = split_params_result(item1=params(1:p), item2=params(p + 1:p + q))
end function split_params

function arma_match_objective(params, acf_emp, pacf_emp, p, q, mode, &
    & pacf_weight, npsi) result(result_value)
! objective for matching empirical and theoretical acf/pacf
real(dp), intent(in) :: params(:), acf_emp(:), pacf_emp(:), pacf_weight
integer, intent(in) :: p, q, npsi
character(len=*), intent(in) :: mode
real(dp) :: result_value
type(split_params_result) :: split_params_value
real(dp), allocatable :: ar(:), ma(:), acf_theo(:), pacf_theo(:), w(:), d(:)
integer :: k
real(dp) :: val
if (.true.) then
    split_params_value = split_params(params, p, q)
    ar = split_params_value%item1
    ma = split_params_value%item2
end if
if (ac_any(abs(params) >= 0.999d0)) then
    result_value = 1d+30
    return
end if
if (.not. is_stationary_ar(ar)) then
    result_value = 1d+30
    return
end if
if (.not. is_invertible_ma(ma)) then
    result_value = 1d+30
    return
end if
k = size(acf_emp)
acf_theo = theoretical_acf_arma(ar, ma, k, npsi)
pacf_theo = theoretical_pacf_arma(ar, ma, k, npsi)
w = 1.0d0 / ac_arange(1, k + 1)
val = 0.0d0
if ((mode == "acf") .or. (mode == "both")) then
    d = acf_emp - acf_theo
    val = val + sum(w * d * d)
end if
if ((mode == "pacf") .or. (mode == "both")) then
    d = pacf_emp - pacf_theo
    val = val + pacf_weight * sum(w * d * d)
end if
result_value = val
end function arma_match_objective

function local_coordinate_search(start, acf_emp, pacf_emp, p, q, mode, &
    & pacf_weight, step0, step_min, shrink, max_rounds, bound, npsi, rng_arg) &
    & result(result_value)
! simple pure-numpy local search
real(dp), intent(in) :: start(:), acf_emp(:), pacf_emp(:), pacf_weight, step0, &
    & step_min, shrink, bound
integer, intent(in) :: p, q, max_rounds, npsi
character(len=*), intent(in) :: mode
type(ac_random_state), intent(in) :: rng_arg
type(local_coordinate_search_result) :: result_value
type(ac_random_state) :: rng
real(dp), allocatable :: x(:), cand(:), direction(:)
real(dp) :: fx, step, sign, fc, norm
integer :: d, rounds, i, ac_loop_index
logical :: improved
rng = rng_arg
if (.false.) rng = ac_random_init()
x = ac_clip(ac_copy(ac_asarray(start)), -bound, bound)
fx = arma_match_objective(x, acf_emp, pacf_emp, p, q, mode, pacf_weight, npsi)
d = size(x)
step = step0
rounds = 0
do while ((step > step_min) .and. (rounds < max_rounds))
    rounds = rounds + 1
    improved = .false.
    do i = 0, d - 1
        sign = -1.0d0
        cand = ac_copy(x)
        cand(i + 1) = ac_clip(cand(i + 1) + sign * step, -bound, bound)
        fc = arma_match_objective(cand, acf_emp, pacf_emp, p, q, mode, &
    & pacf_weight, npsi)
        if (fc < fx) then
            x = cand
            fx = fc
            improved = .true.
        end if
        sign = 1.0d0
        cand = ac_copy(x)
        cand(i + 1) = ac_clip(cand(i + 1) + sign * step, -bound, bound)
        fc = arma_match_objective(cand, acf_emp, pacf_emp, p, q, mode, &
    & pacf_weight, npsi)
        if (fc < fx) then
            x = cand
            fx = fc
            improved = .true.
        end if
    end do
    if (.not. improved .and. (d > 0)) then
        do ac_loop_index = 0, 2 * d - 1
            direction = ac_normal_vec(rng, 0.0d0, 1.0d0, d)
            norm = ac_norm(direction)
            if (norm > 0.0d0) direction = direction / norm
            cand = ac_clip(x + step * direction, -bound, bound)
            fc = arma_match_objective(cand, acf_emp, pacf_emp, p, q, mode, &
    & pacf_weight, npsi)
            if (fc < fx) then
                x = cand
                fx = fc
                improved = .true.
                exit
            end if
        end do
    end if
    if (.not. improved) step = step * shrink
end do
result_value = local_coordinate_search_result(item1=x, item2=fx)
end function local_coordinate_search

function fit_arma_initial_numpy(x, p, q, k, mode, pacf_weight, n_starts, &
    & step0, step_min, shrink, max_rounds, bound, npsi, seed) &
    & result(result_value)
! fit an initial arma(p, q) guess from the first k empirical acf/pacf values
!     using only numpy
!     returns a dictionary with ar, ma, empirical/theoretical acf/pacf, and
!     the objective value
real(dp), intent(in) :: x(:), pacf_weight, step0, step_min, shrink, bound
integer, intent(in) :: p, q, k, n_starts, max_rounds, npsi, seed
character(len=*), intent(in) :: mode
type(fit_arma_initial_numpy_result) :: result_value
real(dp), allocatable :: acf_emp(:), pacf_emp(:), starts(:), ar0(:), ma0(:), &
    & s(:), best_params(:), params(:), ar_hat(:), ma_hat(:)
integer :: d, ac_loop_index, s_index
type(ac_random_state) :: rng
real(dp) :: best_obj, obj
type(local_coordinate_search_result) :: local_coordinate_search_value
type(split_params_result) :: split_params_value
if ((p < 0) .or. (q < 0)) error stop "p and q must be nonnegative"
if ((p == 0) .and. (q == 0)) error stop "at least one of p, q must be positive"
acf_emp = empirical_acf(x, k)
pacf_emp = empirical_pacf(x, k)
d = p + q
rng = ac_random_init(seed)
starts = [real(dp) :: ]
ar0 = yule_walker_ar_start(acf_emp, p)
ma0 = ac_zeros(q)
starts = [starts, [ar0, ma0]]
starts = [starts, ac_zeros(d)]
do ac_loop_index = 0, max(0, n_starts - size(starts)) - 1
    s = ac_uniform_vec(rng, -0.6d0, 0.6d0, d)
    starts = [starts, s]
end do
best_params = ac_zeros(0)
best_obj = 1d+300
do s_index = 0, size(starts) - 1
    s = starts(s_index + 1)
    if (.true.) then
        local_coordinate_search_value = local_coordinate_search(s, acf_emp, &
    & pacf_emp, p, q, mode, pacf_weight, step0, step_min, shrink, max_rounds, &
    & bound, npsi, rng)
        params = local_coordinate_search_value%item1
        obj = local_coordinate_search_value%item2
    end if
    if (obj < best_obj) then
        best_obj = obj
        best_params = params
    end if
end do
if (.true.) then
    split_params_value = split_params(best_params, p, q)
    ar_hat = split_params_value%item1
    ma_hat = split_params_value%item2
end if
result_value = fit_arma_initial_numpy_result(ar=ar_hat, ma=ma_hat, objective &
    & =best_obj, acf_emp=acf_emp, acf_theo=theoretical_acf_arma(ar_hat, &
    & ma_hat, k, npsi), pacf_emp=pacf_emp, pacf_theo &
    & =theoretical_pacf_arma(ar_hat, ma_hat, k, npsi))
end function fit_arma_initial_numpy

pure function compare_values(emp, theo) result(result_value)
! return lag, empirical, theoretical, difference
real(dp), intent(in) :: emp(:), theo(:)
real(dp), allocatable :: result_value(:, :)
result_value = ac_column_stack(ac_arange(1, size(emp) + 1), emp, theo, emp - &
    & theo)
end function compare_values

subroutine print_table(title, table)
character(len=*), intent(in) :: title
real(dp), intent(in) :: table(:, :)
integer :: tuple_index
real(dp), allocatable :: tuple_value(:)
real(dp) :: lag, emp, theo, diff
write(*, "(a)") title
write(*, "(a)") " lag    empirical    theoretical    difference"
do tuple_index = 0, ac_shape_dim(table, 1) - 1
    lag = table(tuple_index + 1, 1)
    emp = table(tuple_index + 1, 2)
    theo = table(tuple_index + 1, 3)
    diff = table(tuple_index + 1, 4)
    write(*, "(a)") ac_format_int(int(lag), 4) // "   " // &
    & ac_format_fixed(emp, 6, 10) // "   " // ac_format_fixed(theo, 6, 11) // &
    & "   " // ac_format_fixed(diff, 6, 11)
end do
print *
end subroutine print_table

subroutine main()
integer, parameter :: n = 4000
real(dp), parameter :: ar_true(2) = [0.6d0, -0.25d0], ma_true(2) = [0.5d0, &
    & 0.2d0], sigma = 1.0d0
integer, parameter :: k = 10, seed = 123
type(fit_arma_initial_numpy_result) :: res
real(dp), allocatable :: acf_table(:, :), pacf_table(:, :)
res = fit_arma_initial_numpy(simulate_arma(n, ar_true, ma_true, sigma, 1500, &
    & seed), 2, 2, k, "both", 0.5d0, 30, 0.25d0, 0.0001d0, 0.5d0, 10, 0.98d0, &
    & 1500, seed)
acf_table = compare_values(res%acf_emp, res%acf_theo)
pacf_table = compare_values(res%pacf_emp, res%pacf_theo)
write(*, "(a)") "true ar = " // ac_format_array(ac_round(ar_true, 6))
write(*, "(a)") "true ma = " // ac_format_array(ac_round(ma_true, 6))
print *
write(*, "(a)") "initial guess from acf/pacf matching"
write(*, "(a)") "ar_hat = " // ac_format_array(ac_round(res%ar, 6))
write(*, "(a)") "ma_hat = " // ac_format_array(ac_round(res%ma, 6))
write(*, "(a)") "objective = " // &
    & ac_format_default(ac_float(ac_round(res%objective, 8)))
print *
call print_table("acf", acf_table)
call print_table("pacf", pacf_table)
end subroutine main

subroutine run_main()
call main()
end subroutine run_main

end module xarma_sim_fit_acf_pacf_p
