! generated by Array Compiler
module xarma_tmp
use kind_mod, only: dp
use ac_string_mod, only: ac_lower, ac_format_default, ac_format_fixed, &
    & ac_format_scientific, ac_format_int, ac_format_array, &
    & ac_set_printoptions
use ac_random_support, only: ac_random_state, ac_random_init, ac_gauss
use ac_numpy_mod
implicit none

private
public :: is_stationary_ar, is_invertible_ma, simulate_arma, empirical_acf, &
    & pacf_from_acf, empirical_pacf, impulse_response_arma, &
    & theoretical_acovf_arma, theoretical_acf_arma, theoretical_pacf_arma, &
    & compare_values, print_table, main
public :: run_main

contains

pure function is_stationary_ar(ar) result(result_value)
! return true if the ar polynomial has roots outside the unit circle
real(dp), intent(in) :: ar(:)
logical :: result_value
real(dp), allocatable :: poly(:)
complex(dp), allocatable :: roots(:)
if (size(ar) == 0) then
    result_value = .true.
    return
end if
poly = [-ac_reverse(ar), 1.0d0]
roots = ac_roots(poly)
result_value = all(abs(roots) > 1.0d0)
end function is_stationary_ar

pure function is_invertible_ma(ma) result(result_value)
! return true if the ma polynomial has roots outside the unit circle
real(dp), intent(in) :: ma(:)
logical :: result_value
real(dp), allocatable :: poly(:)
complex(dp), allocatable :: roots(:)
if (size(ma) == 0) then
    result_value = .true.
    return
end if
poly = [ac_reverse(ma), 1.0d0]
roots = ac_roots(poly)
result_value = all(abs(roots) > 1.0d0)
end function is_invertible_ma

function simulate_arma(n, ar_arg, ma_arg, sigma, burn, seed) &
    & result(result_value)
! simulate an arma(p, q) series
!     x[t] = sum ar[i-1] * x[t-i] + eps[t] + sum ma[j-1] * eps[t-j]
integer, intent(in) :: n, burn, seed
real(dp), intent(in) :: ar_arg(:), ma_arg(:), sigma
real(dp), allocatable :: result_value(:)
real(dp), allocatable :: ar(:), ma(:), eps(:), x(:)
integer :: p, q, r, total, t
type(ac_random_state) :: rng
real(dp) :: ar_part, ma_part
ar = ar_arg
ma = ma_arg
if (size(ar) == 0) ar = ac_zeros(0)
if (size(ma) == 0) ma = ac_zeros(0)
if (.not. is_stationary_ar(ar)) error stop &
    & "ar does not define a stationary process"
p = size(ar)
q = size(ma)
r = max(p, q)
total = (n + burn) + r
rng = ac_random_init(seed)
eps = ac_normal_vec(rng, 0.0d0, sigma, total)
x = ac_zeros(total)
do t = r, total - 1
    ar_part = 0.0d0
    if (p > 0) ar_part = ac_dot(ar, x(t:(t - p) + 1:-1))
    ma_part = eps(t + 1)
    if (q > 0) ma_part = ma_part + ac_dot(ma, eps(t:(t - q) + 1:-1))
    x(t + 1) = ar_part + ma_part
end do
result_value = x((burn + r) + 1:size(x))
end function simulate_arma

pure function empirical_acf(x, k) result(result_value)
! sample autocorrelations at lags 1,...,k
real(dp), intent(in) :: x(:)
integer, intent(in) :: k
real(dp), allocatable :: result_value(:)
integer :: n, lag
real(dp), allocatable :: xc(:), acf(:)
real(dp) :: denom
n = size(x)
if (k >= n) error stop "k must be less than len(x)"
xc = x - ac_mean(x)
denom = ac_dot(xc, xc)
acf = ac_empty(k)
do lag = 1, k
    acf(lag) = ac_dot(ac_slice(xc, 0, -lag), xc(lag + 1:size(xc))) / denom
end do
result_value = acf
end function empirical_acf

pure function pacf_from_acf(rho) result(result_value)
! given rho[0],...,rho[k], return pacf at lags 1,...,k
!     using durbin-levinson recursion
real(dp), intent(in) :: rho(:)
real(dp), allocatable :: result_value(:)
integer :: k, m, j
real(dp), allocatable :: phi(:, :), pacf(:)
real(dp) :: v, num
k = size(rho) - 1
if (k < 1) then
    result_value = ac_zeros(0)
    return
end if
phi = ac_zeros2(k + 1, k + 1)
pacf = ac_zeros(k + 1)
call ac_set_item2(phi, 1, 1, rho(2))
pacf(2) = rho(2)
v = 1.0d0 - (rho(2) ** 2)
do m = 2, k
    num = rho(m + 1)
    do j = 1, m - 1
        num = num - ac_item2(phi, m - 1, j) * rho((m - j) + 1)
    end do
    call ac_set_item2(phi, m, m, num / v)
    pacf(m + 1) = ac_item2(phi, m, m)
    do j = 1, m - 1
        call ac_set_item2(phi, m, j, ac_item2(phi, m - 1, j) - (ac_item2(phi, &
    & m, m) * ac_item2(phi, m - 1, m - j)))
    end do
    v = v * 1.0d0 - (ac_item2(phi, m, m) ** 2)
end do
result_value = pacf(2:size(pacf))
end function pacf_from_acf

pure function empirical_pacf(x, k) result(result_value)
! sample pacf at lags 1,...,k
real(dp), intent(in) :: x(:)
integer, intent(in) :: k
real(dp), allocatable :: result_value(:)
real(dp), allocatable :: acf(:), rho(:)
acf = empirical_acf(x, k)
rho = ac_empty(k + 1)
rho(1) = 1.0d0
rho(2:size(rho)) = acf
result_value = pacf_from_acf(rho)
end function empirical_pacf

function impulse_response_arma(ar_arg, ma_arg, n) result(result_value)
! return psi[0],...,psi[n-1] where
!     x[t] = sum_{j>=0} psi[j] * eps[t-j]
real(dp), intent(in) :: ar_arg(:), ma_arg(:)
integer, intent(in) :: n
real(dp), allocatable :: result_value(:)
real(dp), allocatable :: ar(:), ma(:), psi(:)
integer :: p, q, j, m, i
real(dp) :: s
ar = ar_arg
ma = ma_arg
if (size(ar) == 0) ar = ac_zeros(0)
if (size(ma) == 0) ma = ac_zeros(0)
p = size(ar)
q = size(ma)
psi = ac_zeros(n)
psi(1) = 1.0d0
do j = 1, n - 1
    s = 0.0d0
    if (j <= q) s = s + ma(j)
    m = min(p, j)
    do i = 1, m
        s = s + ar(i) * psi((j - i) + 1)
    end do
    psi(j + 1) = s
end do
result_value = psi
end function impulse_response_arma

function theoretical_acovf_arma(ar_arg, ma_arg, sigma, k) result(result_value)
! return theoretical autocovariances gamma(0),...,gamma(k)
!     for a stationary arma(p, q)
!     uses exact linear equations for the first max(p, q) lags,
!     then the ar recursion for higher lags
real(dp), intent(in) :: ar_arg(:), ma_arg(:), sigma
integer, intent(in) :: k
real(dp), allocatable :: result_value(:)
real(dp), allocatable :: ar(:), ma(:), theta(:), psi(:), a(:, :), b(:), &
    & gamma0_to_m(:), gamma(:)
integer :: p, q, m, h, i, j
real(dp) :: s
ar = ar_arg
ma = ma_arg
if (size(ar) == 0) ar = ac_zeros(0)
if (size(ma) == 0) ma = ac_zeros(0)
if (.not. is_stationary_ar(ar)) error stop &
    & "ar does not define a stationary process"
p = size(ar)
q = size(ma)
m = max(p, q)
theta = ac_empty(q + 1)
theta(1) = 1.0d0
if (q > 0) call ac_set_slice(theta, 1, size(theta), ma)
psi = impulse_response_arma(ar, ma, q + 1)
a = ac_zeros2(m + 1, m + 1)
b = ac_zeros(m + 1)
do h = 0, m
    call ac_set_item2(a, h, h, 1.0d0)
    do i = 1, p
        j = abs(h - i)
        call ac_set_item2(a, h, j, ac_item2(a, h, j) - ar(i))
    end do
    s = 0.0d0
    do j = h, q
        s = s + theta(j + 1) * psi((j - h) + 1)
    end do
    b(h + 1) = (sigma ** 2) * s
end do
gamma0_to_m = ac_solve_linear(a, b)
gamma = ac_zeros(k + 1)
gamma(1:m + 1) = gamma0_to_m(1:min(m, k) + 1)
do h = m + 1, k
    if (p == 0) then
        gamma(h + 1) = 0.0d0
    else
        gamma(h + 1) = ac_dot(ar, gamma(h:h - (p + 1) + 2:-1))
    end if
end do
result_value = gamma
end function theoretical_acovf_arma

function theoretical_acf_arma(ar, ma, sigma, k) result(result_value)
! return theoretical autocorrelations rho(1),...,rho(k)
real(dp), intent(in) :: ar(:), ma(:), sigma
integer, intent(in) :: k
real(dp), allocatable :: result_value(:)
real(dp), allocatable :: gamma(:)
gamma = theoretical_acovf_arma(ar, ma, sigma, k)
result_value = gamma(2:size(gamma)) / gamma(1)
end function theoretical_acf_arma

function theoretical_pacf_arma(ar, ma, sigma, k) result(result_value)
! return theoretical pacf at lags 1,...,k
real(dp), intent(in) :: ar(:), ma(:), sigma
integer, intent(in) :: k
real(dp), allocatable :: result_value(:)
real(dp), allocatable :: acf(:), rho(:)
acf = theoretical_acf_arma(ar, ma, sigma, k)
rho = ac_empty(k + 1)
rho(1) = 1.0d0
rho(2:size(rho)) = acf
result_value = pacf_from_acf(rho)
end function theoretical_pacf_arma

pure function compare_values(emp, theo) result(result_value)
! return lag, empirical, theoretical, difference
real(dp), intent(in) :: emp(:), theo(:)
real(dp), allocatable :: result_value(:, :)
real(dp), allocatable :: lags(:), diff(:)
if (size(emp) /= size(theo)) error stop "emp and theo must have the same length"
lags = ac_arange(1, size(emp) + 1)
diff = emp - theo
result_value = ac_column_stack(lags, emp, theo, diff)
end function compare_values

subroutine print_table(title, table)
character(len=*), intent(in) :: title
real(dp), intent(in) :: table(:, :)
integer :: tuple_index
real(dp), allocatable :: tuple_value(:)
real(dp) :: lag, emp, theo, diff
write(*, "(a)") title
write(*, "(a)") " lag    empirical    theoretical    difference"
do tuple_index = 0, ac_shape_dim(table, 1) - 1
    lag = ac_item2(table, tuple_index, 0)
    emp = ac_item2(table, tuple_index, 1)
    theo = ac_item2(table, tuple_index, 2)
    diff = ac_item2(table, tuple_index, 3)
    write(*, "(a)") ac_format_int(int(lag), 4) // "   " // &
    & ac_format_fixed(emp, 6, 10) // "   " // ac_format_fixed(theo, 6, 11) // &
    & "   " // ac_format_fixed(diff, 6, 11)
end do
print *
end subroutine print_table

subroutine main()
integer, parameter :: n = 5000
real(dp), allocatable :: ar(:), ma(:), x(:), emp_acf(:), theo_acf(:), &
    & acf_table(:, :), emp_pacf(:), theo_pacf(:), pacf_table(:, :)
real(dp) :: sigma
integer :: k, seed
ar = ac_array([0.6d0, -0.2d0])
! ar(2)
ma = ac_array([0.5d0])
! ma(1)
sigma = 1.0d0
k = 10
seed = 123
write(*, "(a)") "n:" // " " // ac_format_int(n, 0)
x = simulate_arma(n, ar, ma, sigma, 1000, seed)
emp_acf = empirical_acf(x, k)
theo_acf = theoretical_acf_arma(ar, ma, sigma, k)
acf_table = compare_values(emp_acf, theo_acf)
emp_pacf = empirical_pacf(x, k)
theo_pacf = theoretical_pacf_arma(ar, ma, sigma, k)
pacf_table = compare_values(emp_pacf, theo_pacf)
write(*, "(a)") "ar =" // " " // ac_format_array(ar)
write(*, "(a)") "ma =" // " " // ac_format_array(ma)
write(*, "(a)") "stationary ar part =" // " " // &
    & ac_format_default(is_stationary_ar(ar))
write(*, "(a)") "invertible ma part =" // " " // &
    & ac_format_default(is_invertible_ma(ma))
print *
write(*, "(a)") "first 10 simulated values:"
write(*, "(a)") ac_format_array(ac_round(x(1:10), 4))
print *
call print_table("acf", acf_table)
call print_table("pacf", pacf_table)
end subroutine main

subroutine run_main()
call main()
end subroutine run_main

end module xarma_tmp
