"""Fortran backend skeleton."""

from __future__ import annotations

from dataclasses import dataclass, field

from ...ir.module import Module
from ...ir.nodes import (
    Assignment,
    Append,
    ArrayTypeRef,
    AugmentedAssignment,
    BinaryOp,
    BinaryOperator,
    BooleanOp,
    Call,
    ConditionalExpr,
    Compare,
    CompareOperator,
    Constant,
    ExprStatement,
    FieldAccess,
    FieldAssignment,
    ForRange,
    Function,
    If,
    IndexAssignment,
    IndexAccess,
    ListComprehension,
    Print,
    Raise,
    RecordLiteral,
    RecordTypeRef,
    Return,
    ScalarType,
    UnaryOp,
    UnaryOperator,
    ValueRef,
)
from .formatter import wrap_fortran_source
from .helpers import HelperRegistry


@dataclass
class FortranBackend:
    helper_registry: HelperRegistry = field(default_factory=HelperRegistry)

    def emit(self, module: Module) -> str:
        helper_keys = self._required_helpers(module)
        export_names = self._export_names(module)
        lines: list[str] = [
            "! generated by Array Compiler",
            f"module {module.name}",
            *self._emit_use_lines(helper_keys),
            "implicit none",
            "",
        ]
        lines.extend(self._emit_visibility_lines(module, export_names))
        for record in module.records:
            lines.extend(self._emit_record(record))
            lines.append("")
        lines.extend([
            "contains",
            "",
            *self._emit_lower_helper(),
            "",
        ])
        for fn in module.functions:
            lines.extend(self._emit_function(fn))
            lines.append("")
        if module.program is not None:
            lines.extend(self._emit_program(module.program))
            lines.append("")
        lines.extend([f"end module {module.name}", ""])
        return wrap_fortran_source("\n".join(lines), max_len=132)

    def _emit_use_lines(self, helper_keys: set[str]) -> list[str]:
        lines: list[str] = ["use kind_mod, only: dp"]
        if "ac_random" in helper_keys:
            lines.append("use ac_random_support, only: ac_random_state, ac_random_init, ac_gauss")
        return lines

    def _emit_visibility_lines(self, module: Module, export_names: list[str]) -> list[str]:
        if not module.library_mode and not export_names:
            return []
        lines = ["private"]
        if export_names:
            lines.append("public :: " + ", ".join(export_names))
        if module.records:
            lines.append("public :: " + ", ".join(record.name for record in module.records))
        if module.program is not None:
            lines.append(f"public :: {module.program.name}")
        lines.append("")
        return lines

    def _emit_record(self, record) -> list[str]:
        lines = [f"type :: {record.name}"]
        if not record.fields:
            lines.append("    integer :: unused = 0")
        for name, typ in record.fields:
            lines.append(f"    {self._declare_component(name, typ)}")
        lines.append(f"end type {record.name}")
        return lines

    def _emit_lower_helper(self) -> list[str]:
        return [
            "pure function ac_lower(value) result(out)",
            "implicit none",
            "character(len=*), intent(in) :: value",
            "character(len=len(value)) :: out",
            "integer :: i, code",
            "out = value",
            "do i = 1, len(value)",
            "    code = iachar(value(i:i))",
            "    if (code >= iachar('A') .and. code <= iachar('Z')) then",
            "        out(i:i) = achar(code + 32)",
            "    end if",
            "end do",
            "end function ac_lower",
        ]

    def _emit_function(self, fn: Function) -> list[str]:
        if fn.result_type is None:
            arg_text = ", ".join(name for name, _ in fn.args)
            lines = [f"subroutine {fn.name}({arg_text})", "implicit none"]
            for name, typ in fn.args:
                lines.append(self._declare_arg(name, typ))
            for name, typ in fn.locals:
                lines.append(self._declare_local(name, typ))
            for stmt in fn.body:
                lines.extend(self._emit_stmt(stmt, result_name=""))
            lines.append(f"end subroutine {fn.name}")
            return lines

        result_name = "result_value"
        arg_text = ", ".join(name for name, _ in fn.args)
        lines = [f"function {fn.name}({arg_text}) result({result_name})", "implicit none"]
        for name, typ in fn.args:
            lines.append(self._declare_arg(name, typ))
        for name, typ in fn.locals:
            lines.append(self._declare_local(name, typ))
        lines.append(self._declare_result(result_name, fn.result_type))
        for stmt in fn.body:
            lines.extend(self._emit_stmt(stmt, result_name))
        lines.append(f"end function {fn.name}")
        return lines

    def _emit_program(self, program) -> list[str]:
        lines = [f"subroutine {program.name}()", "implicit none"]
        for stmt in program.body:
            lines.extend(self._emit_stmt(stmt, result_name=""))
        lines.append(f"end subroutine {program.name}")
        return lines

    def _emit_stmt(self, stmt: object, result_name: str) -> list[str]:
        if isinstance(stmt, Assignment):
            if isinstance(stmt.value, Call) and stmt.value.func == "ac_array_literal":
                return [f"{stmt.target.name} = {self._emit_array_literal(stmt.value.args, stmt.target.name)}"]
            return [f"{stmt.target.name} = {self._emit_expr(stmt.value)}"]
        if isinstance(stmt, Append):
            return [f"{stmt.target.name} = [{stmt.target.name}, {self._emit_expr(stmt.value)}]"]
        if isinstance(stmt, IndexAssignment):
            return [f"{self._emit_expr(stmt.target)}({self._emit_expr(stmt.index)} + 1) = {self._emit_expr(stmt.value)}"]
        if isinstance(stmt, FieldAssignment):
            return [f"{self._emit_expr(stmt.target)}%{stmt.field} = {self._emit_expr(stmt.value)}"]
        if isinstance(stmt, AugmentedAssignment):
            target = stmt.target.name
            value = self._emit_expr(stmt.value)
            return [f"{target} = ({target} {stmt.op.value} {value})"]
        if isinstance(stmt, Return):
            if stmt.value is not None and result_name:
                return [f"{result_name} = {self._emit_expr(stmt.value)}", "return"]
            return ["return"]
        if isinstance(stmt, Raise):
            return [f'error stop {self._emit_string(stmt.message)}']
        if isinstance(stmt, Print):
            if not stmt.values:
                return ["print *"]
            parts = ", ".join(self._emit_expr(value) for value in stmt.values)
            return [f"print *, {parts}"]
        if isinstance(stmt, ExprStatement):
            if isinstance(stmt.expr, Call):
                return [f"call {stmt.expr.func}({', '.join(self._emit_expr(arg) for arg in stmt.expr.args)})"]
            raise NotImplementedError(f"unsupported expression statement: {stmt.expr!r}")
        if isinstance(stmt, If):
            lines = [f"if ({self._emit_expr(stmt.test)}) then"]
            for inner in stmt.body:
                lines.extend("    " + line for line in self._emit_stmt(inner, result_name))
            if stmt.orelse:
                lines.append("else")
                for inner in stmt.orelse:
                    lines.extend("    " + line for line in self._emit_stmt(inner, result_name))
            lines.append("end if")
            return lines
        if isinstance(stmt, ForRange):
            start = self._emit_expr(stmt.start) if stmt.start is not None else "0"
            step = self._emit_expr(stmt.step) if stmt.step is not None else "1"
            if stmt.step is None:
                stop = f"({self._emit_expr(stmt.stop)} - 1)"
            else:
                stop = self._emit_expr(stmt.stop)
            lines = [f"do {stmt.target} = {start}, {stop}, {step}"]
            for inner in stmt.body:
                lines.extend("    " + line for line in self._emit_stmt(inner, result_name))
            lines.append("end do")
            return lines
        raise NotImplementedError(f"unsupported IR statement: {type(stmt).__name__}")

    def _emit_expr(self, expr: object) -> str:
        if isinstance(expr, ValueRef):
            return expr.name
        if isinstance(expr, FieldAccess):
            return f"{self._emit_expr(expr.value)}%{expr.field}"
        if isinstance(expr, IndexAccess):
            return f"{self._emit_expr(expr.value)}({self._emit_expr(expr.index)} + 1)"
        if isinstance(expr, RecordLiteral):
            fields = ", ".join(f"{name}={self._emit_expr(value)}" for name, value in expr.fields)
            return f"{expr.type_name}({fields})"
        if isinstance(expr, Constant):
            if isinstance(expr.value, str):
                return self._emit_string(expr.value)
            if isinstance(expr.value, bool):
                return ".true." if expr.value else ".false."
            if isinstance(expr.value, float):
                return self._emit_real(expr.value)
            return str(expr.value)
        if isinstance(expr, Call):
            if expr.func == "ac_array_literal":
                return self._emit_array_literal(expr.args, "")
            if expr.func == "ac_repeat":
                return f"spread({self._emit_expr(expr.args[0])}, 1, {self._emit_expr(expr.args[1])})"
            if expr.func == "ac_concat":
                return "[" + ", ".join(self._emit_expr(arg) for arg in expr.args) + "]"
            args = ", ".join(self._emit_expr(arg) for arg in expr.args)
            return f"{expr.func}({args})"
        if isinstance(expr, BinaryOp):
            if expr.op == BinaryOperator.POW:
                return f"({self._emit_expr(expr.left)} ** {self._emit_expr(expr.right)})"
            return f"({self._emit_expr(expr.left)} {expr.op.value} {self._emit_expr(expr.right)})"
        if isinstance(expr, UnaryOp):
            if expr.op == UnaryOperator.NOT:
                return f"(.not. {self._emit_expr(expr.operand)})"
            return f"({expr.op.value}{self._emit_expr(expr.operand)})"
        if isinstance(expr, Compare):
            op_map = {
                CompareOperator.EQ: "==",
                CompareOperator.NE: "/=",
                CompareOperator.LT: "<",
                CompareOperator.LE: "<=",
                CompareOperator.GT: ">",
                CompareOperator.GE: ">=",
            }
            return f"({self._emit_expr(expr.left)} {op_map[expr.op]} {self._emit_expr(expr.right)})"
        if isinstance(expr, BooleanOp):
            op = ".and." if expr.op == "and" else ".or."
            return "(" + f" {op} ".join(self._emit_expr(value) for value in expr.values) + ")"
        if isinstance(expr, ConditionalExpr):
            return f"merge({self._emit_expr(expr.body)}, {self._emit_expr(expr.orelse)}, {self._emit_expr(expr.test)})"
        if isinstance(expr, ListComprehension):
            return self._emit_list_comp(expr)
        return str(expr)

    def _declare_arg(self, name: str, value_type: object) -> str:
        if isinstance(value_type, ArrayTypeRef):
            return f"{self._type_name(value_type.element_type)}, intent(in) :: {name}(:)"
        if value_type == ScalarType.STRING:
            return f"character(len=*), intent(in) :: {name}"
        return f"{self._type_name(value_type)}, intent(in) :: {name}"

    def _declare_local(self, name: str, value_type: object) -> str:
        if isinstance(value_type, ArrayTypeRef):
            return f"{self._type_name(value_type)} , allocatable :: {name}(:)"
        return f"{self._type_name(value_type)} :: {name}"

    def _declare_result(self, name: str, value_type: object) -> str:
        if isinstance(value_type, ArrayTypeRef):
            return f"{self._type_name(value_type.element_type)}, allocatable :: {name}(:)"
        return f"{self._type_name(value_type)} :: {name}"

    def _declare_component(self, name: str, value_type: object) -> str:
        return f"{self._type_name(value_type)} :: {name}"

    def _emit_string(self, value: str) -> str:
        escaped = value.replace("'", "''")
        return f"'{escaped}'"

    def _emit_real(self, value: float) -> str:
        text = repr(value).lower()
        if "e" in text:
            return text.replace("e", "d")
        return f"{text}d0"

    def _type_name(self, value_type: object) -> str:
        if isinstance(value_type, RecordTypeRef):
            return f"type({value_type.name})"
        if isinstance(value_type, ArrayTypeRef):
            return self._type_name(value_type.element_type)
        mapping = {
            ScalarType.INTEGER: "integer",
            ScalarType.REAL64: "real(dp)",
            ScalarType.LOGICAL: "logical",
            ScalarType.STRING: "character(len=:), allocatable",
        }
        return mapping[value_type]

    def _emit_array_literal(self, values: tuple[object, ...], target_name: str) -> str:
        if not values:
            return "[real(dp) :: ]"
        return "[" + ", ".join(self._emit_expr(value) for value in values) + "]"

    def _emit_list_comp(self, expr: ListComprehension) -> str:
        if isinstance(expr.iterable, Call) and expr.iterable.func == "range":
            args = expr.iterable.args
            if len(args) == 1:
                start = "0"
                stop = f"({self._emit_expr(args[0])} - 1)"
                step = "1"
            elif len(args) == 2:
                start = self._emit_expr(args[0])
                stop = f"({self._emit_expr(args[1])} - 1)"
                step = "1"
            else:
                start = self._emit_expr(args[0])
                stop = self._emit_expr(args[1])
                step = self._emit_expr(args[2])
            body_expr = self._emit_expr_with_binding(expr.body, {expr.target: expr.target})
            return f"[( {body_expr}, {expr.target} = {start}, {stop}, {step} )]"

        index_name = f"{expr.target}_index"
        iterable_expr = self._emit_expr(expr.iterable)
        bound_body = self._emit_expr_with_binding(expr.body, {expr.target: f"{iterable_expr}({index_name} + 1)"})
        return f"[( {bound_body}, {index_name} = 0, size({iterable_expr}) - 1 )]"

    def _emit_expr_with_binding(self, expr: object, bindings: dict[str, str]) -> str:
        if isinstance(expr, ValueRef) and expr.name in bindings:
            return bindings[expr.name]
        if isinstance(expr, Constant):
            return self._emit_expr(expr)
        if isinstance(expr, BinaryOp):
            if expr.op == BinaryOperator.POW:
                return f"({self._emit_expr_with_binding(expr.left, bindings)} ** {self._emit_expr_with_binding(expr.right, bindings)})"
            return f"({self._emit_expr_with_binding(expr.left, bindings)} {expr.op.value} {self._emit_expr_with_binding(expr.right, bindings)})"
        if isinstance(expr, UnaryOp):
            if expr.op == UnaryOperator.NOT:
                return f"(.not. {self._emit_expr_with_binding(expr.operand, bindings)})"
            return f"({expr.op.value}{self._emit_expr_with_binding(expr.operand, bindings)})"
        if isinstance(expr, Call):
            if expr.func in {"abs", "max", "min", "exp", "sqrt", "log", "int", "floor", "size"}:
                return f"{expr.func}(" + ", ".join(self._emit_expr_with_binding(arg, bindings) for arg in expr.args) + ")"
        return self._emit_expr(expr)

    def _required_helpers(self, module: Module) -> set[str]:
        helper_keys: set[str] = set()

        def visit(value: object) -> None:
            if isinstance(value, Call) and value.func in {"ac_random_init", "ac_gauss"}:
                helper_keys.add("ac_random")
            elif isinstance(value, RecordTypeRef) and value.name == "ac_random_state":
                helper_keys.add("ac_random")

            if isinstance(value, Module):
                for record in value.records:
                    visit(record)
                for function in value.functions:
                    visit(function)
                if value.program is not None:
                    visit(value.program)
                return

            if isinstance(value, Function):
                for _, typ in value.args:
                    visit(typ)
                for _, typ in value.locals:
                    visit(typ)
                if value.result_type is not None:
                    visit(value.result_type)
                for stmt in value.body:
                    visit(stmt)
                return

            if hasattr(value, "__dataclass_fields__"):
                for field_name in value.__dataclass_fields__:
                    visit(getattr(value, field_name))
                return

            if isinstance(value, dict):
                for item in value.values():
                    visit(item)
                return

            if isinstance(value, (list, tuple, set)):
                for item in value:
                    visit(item)

        visit(module)
        return helper_keys

    def _export_names(self, module: Module) -> list[str]:
        if module.exports:
            return list(dict.fromkeys(module.exports))
        return [fn.name for fn in module.functions]
