"""Fortran backend skeleton."""

from __future__ import annotations

from dataclasses import dataclass, field

from ...ir.module import Module
from ...ir.nodes import (
    Assignment,
    AugmentedAssignment,
    BinaryOp,
    BinaryOperator,
    BooleanOp,
    Call,
    Compare,
    CompareOperator,
    Constant,
    ExprStatement,
    FieldAccess,
    FieldAssignment,
    ForRange,
    Function,
    If,
    Print,
    Raise,
    RecordLiteral,
    RecordTypeRef,
    Return,
    ScalarType,
    UnaryOp,
    UnaryOperator,
    ValueRef,
)
from .helpers import HelperRegistry


@dataclass
class FortranBackend:
    helper_registry: HelperRegistry = field(default_factory=HelperRegistry)

    def emit(self, module: Module) -> str:
        lines: list[str] = [
            "! generated by Array Compiler",
            f"module {module.name}",
            "implicit none",
            "",
        ]
        for record in module.records:
            lines.extend(self._emit_record(record))
            lines.append("")
        lines.extend([
            "contains",
            "",
            *self._emit_lower_helper(),
            "",
        ])
        for fn in module.functions:
            lines.extend(self._emit_function(fn))
            lines.append("")
        if module.program is not None:
            lines.extend(self._emit_program(module.program))
            lines.append("")
        lines.extend([f"end module {module.name}", ""])
        return "\n".join(lines)

    def _emit_record(self, record) -> list[str]:
        lines = [f"type :: {record.name}"]
        if not record.fields:
            lines.append("    integer :: unused = 0")
        for name, typ in record.fields:
            lines.append(f"    {self._declare_component(name, typ)}")
        lines.append(f"end type {record.name}")
        return lines

    def _emit_lower_helper(self) -> list[str]:
        return [
            "pure function ac_lower(value) result(out)",
            "implicit none",
            "character(len=*), intent(in) :: value",
            "character(len=len(value)) :: out",
            "integer :: i, code",
            "out = value",
            "do i = 1, len(value)",
            "    code = iachar(value(i:i))",
            "    if (code >= iachar('A') .and. code <= iachar('Z')) then",
            "        out(i:i) = achar(code + 32)",
            "    end if",
            "end do",
            "end function ac_lower",
        ]

    def _emit_function(self, fn: Function) -> list[str]:
        if fn.result_type is None:
            arg_text = ", ".join(name for name, _ in fn.args)
            lines = [f"subroutine {fn.name}({arg_text})", "implicit none"]
            for name, typ in fn.args:
                lines.append(self._declare_arg(name, typ))
            for name, typ in fn.locals:
                lines.append(self._declare_local(name, typ))
            for stmt in fn.body:
                lines.extend(self._emit_stmt(stmt, result_name=""))
            lines.append(f"end subroutine {fn.name}")
            return lines

        result_name = "result_value"
        arg_text = ", ".join(name for name, _ in fn.args)
        lines = [f"function {fn.name}({arg_text}) result({result_name})", "implicit none"]
        for name, typ in fn.args:
            lines.append(self._declare_arg(name, typ))
        for name, typ in fn.locals:
            lines.append(self._declare_local(name, typ))
        lines.append(self._declare_result(result_name, fn.result_type))
        for stmt in fn.body:
            lines.extend(self._emit_stmt(stmt, result_name))
        lines.append(f"end function {fn.name}")
        return lines

    def _emit_program(self, program) -> list[str]:
        lines = [f"subroutine {program.name}()", "implicit none"]
        for stmt in program.body:
            lines.extend(self._emit_stmt(stmt, result_name=""))
        lines.append(f"end subroutine {program.name}")
        return lines

    def _emit_stmt(self, stmt: object, result_name: str) -> list[str]:
        if isinstance(stmt, Assignment):
            return [f"{stmt.target.name} = {self._emit_expr(stmt.value)}"]
        if isinstance(stmt, FieldAssignment):
            return [f"{self._emit_expr(stmt.target)}%{stmt.field} = {self._emit_expr(stmt.value)}"]
        if isinstance(stmt, AugmentedAssignment):
            target = stmt.target.name
            value = self._emit_expr(stmt.value)
            return [f"{target} = ({target} {stmt.op.value} {value})"]
        if isinstance(stmt, Return):
            if stmt.value is not None and result_name:
                return [f"{result_name} = {self._emit_expr(stmt.value)}", "return"]
            return ["return"]
        if isinstance(stmt, Raise):
            return [f'error stop {self._emit_string(stmt.message)}']
        if isinstance(stmt, Print):
            parts = ", ".join(self._emit_expr(value) for value in stmt.values)
            return [f"print *, {parts}"]
        if isinstance(stmt, ExprStatement):
            if isinstance(stmt.expr, Call):
                return [f"call {stmt.expr.func}({', '.join(self._emit_expr(arg) for arg in stmt.expr.args)})"]
            raise NotImplementedError(f"unsupported expression statement: {stmt.expr!r}")
        if isinstance(stmt, If):
            lines = [f"if ({self._emit_expr(stmt.test)}) then"]
            for inner in stmt.body:
                lines.extend("    " + line for line in self._emit_stmt(inner, result_name))
            if stmt.orelse:
                lines.append("else")
                for inner in stmt.orelse:
                    lines.extend("    " + line for line in self._emit_stmt(inner, result_name))
            lines.append("end if")
            return lines
        if isinstance(stmt, ForRange):
            lines = [f"do {stmt.target} = 1, {self._emit_expr(stmt.stop)}"]
            for inner in stmt.body:
                lines.extend("    " + line for line in self._emit_stmt(inner, result_name))
            lines.append("end do")
            return lines
        raise NotImplementedError(f"unsupported IR statement: {type(stmt).__name__}")

    def _emit_expr(self, expr: object) -> str:
        if isinstance(expr, ValueRef):
            return expr.name
        if isinstance(expr, FieldAccess):
            return f"{self._emit_expr(expr.value)}%{expr.field}"
        if isinstance(expr, RecordLiteral):
            fields = ", ".join(f"{name}={self._emit_expr(value)}" for name, value in expr.fields)
            return f"{expr.type_name}({fields})"
        if isinstance(expr, Constant):
            if isinstance(expr.value, str):
                return self._emit_string(expr.value)
            if isinstance(expr.value, bool):
                return ".true." if expr.value else ".false."
            return str(expr.value)
        if isinstance(expr, Call):
            args = ", ".join(self._emit_expr(arg) for arg in expr.args)
            return f"{expr.func}({args})"
        if isinstance(expr, BinaryOp):
            if expr.op == BinaryOperator.POW:
                return f"({self._emit_expr(expr.left)} ** {self._emit_expr(expr.right)})"
            return f"({self._emit_expr(expr.left)} {expr.op.value} {self._emit_expr(expr.right)})"
        if isinstance(expr, UnaryOp):
            if expr.op == UnaryOperator.NOT:
                return f"(.not. {self._emit_expr(expr.operand)})"
            return f"({expr.op.value}{self._emit_expr(expr.operand)})"
        if isinstance(expr, Compare):
            op_map = {
                CompareOperator.EQ: "==",
                CompareOperator.NE: "/=",
                CompareOperator.LT: "<",
                CompareOperator.LE: "<=",
                CompareOperator.GT: ">",
                CompareOperator.GE: ">=",
            }
            return f"({self._emit_expr(expr.left)} {op_map[expr.op]} {self._emit_expr(expr.right)})"
        if isinstance(expr, BooleanOp):
            op = ".and." if expr.op == "and" else ".or."
            return "(" + f" {op} ".join(self._emit_expr(value) for value in expr.values) + ")"
        return str(expr)

    def _declare_arg(self, name: str, value_type: object) -> str:
        if value_type == ScalarType.STRING:
            return f"character(len=*), intent(in) :: {name}"
        return f"{self._type_name(value_type)}, intent(in) :: {name}"

    def _declare_local(self, name: str, value_type: object) -> str:
        return f"{self._type_name(value_type)} :: {name}"

    def _declare_result(self, name: str, value_type: object) -> str:
        return f"{self._type_name(value_type)} :: {name}"

    def _declare_component(self, name: str, value_type: object) -> str:
        return f"{self._type_name(value_type)} :: {name}"

    def _emit_string(self, value: str) -> str:
        escaped = value.replace("'", "''")
        return f"'{escaped}'"

    def _type_name(self, value_type: object) -> str:
        if isinstance(value_type, RecordTypeRef):
            return f"type({value_type.name})"
        mapping = {
            ScalarType.INTEGER: "integer",
            ScalarType.REAL64: "real(8)",
            ScalarType.LOGICAL: "logical",
            ScalarType.STRING: "character(len=:), allocatable",
        }
        return mapping[value_type]
